### ISSUE TITLE
YAML/JSON Support

### ISSUE THREAD

**Issue by 1995parham** [JeremyLoy/config#7]
Is there any plan for supporting these files too?

**Comment by JeremyLoy** [comment]
Hi @1995parham,

In short, no because it’s already done!

Struct fields can have multiple tags, so it’s possible to have a single config struct that supports json, yaml, and env config. 

JSON binding to a struct is already supported via the stdlib. If I were to incorporate it into my library it would just be a thin wrapper, not providing much benefit, really just noise.

Likewise, there already exist many well tested YAML libraries made by other people. I don’t want to redo their work without any clear benefit. Again it would just be a thin wrapper.
